"""Public runner for the usable ODS alpha flow."""

from __future__ import annotations

from dataclasses import dataclass

from .bdna import BDNAPlugin, BusinessBlueprint
from .discovery import FashionDiscoveryPlugin
from .models import ODSRequest, ODSSession, Stage, Status
from .plugins import PluginRegistry
from .ranking import OpportunityRankingPlugin, RankedOpportunity
from .validation import ValidationPlugin, ValidationReport
from .workflow import WorkflowEngine


USABLE_ALPHA_WORKFLOW: tuple[Stage, ...] = (
    Stage.DISCOVERY,
    Stage.RANKING,
    Stage.BDNA,
    Stage.VALIDATION,
)


@dataclass(frozen=True)
class ODSAnalysisResult:
    """Convenient, validated view of a completed ODS alpha session."""

    session: ODSSession
    ranked_opportunities: tuple[RankedOpportunity, ...]
    blueprint: BusinessBlueprint
    validation: ValidationReport

    @property
    def discovered_count(self) -> int:
        discovery = self.session.results[Stage.DISCOVERY].payload
        return len(discovery)


def build_alpha_engine(
    *,
    shortlist_size: int = 5,
    minimum_score: float = 0.0,
) -> WorkflowEngine:
    """Build the currently supported ODS engine."""

    registry = PluginRegistry(
        (
            FashionDiscoveryPlugin(),
            OpportunityRankingPlugin(
                shortlist_size=shortlist_size,
                minimum_score=minimum_score,
            ),
            BDNAPlugin(),
            ValidationPlugin(),
        )
    )
    return WorkflowEngine(registry, workflow=USABLE_ALPHA_WORKFLOW)


def run_ods(
    subject: str,
    *,
    country: str | None = "Norway",
    constraints: tuple[str, ...] = (),
    shortlist_size: int = 5,
    minimum_score: float = 0.0,
) -> ODSAnalysisResult:
    """Run Discovery → Ranking → BDNA → Validation."""

    request = ODSRequest(
        subject=subject,
        country=country,
        constraints=constraints,
    )
    engine = build_alpha_engine(
        shortlist_size=shortlist_size,
        minimum_score=minimum_score,
    )
    session = engine.run(request)

    if session.status is not Status.COMPLETED:
        detail = _failure_detail(session)
        raise RuntimeError(f"ODS analysis failed: {detail}")

    ranking_payload = session.results[Stage.RANKING].payload
    blueprint_payload = session.results[Stage.BDNA].payload
    validation_payload = session.results[Stage.VALIDATION].payload
    if not isinstance(ranking_payload, tuple) or not all(
        isinstance(item, RankedOpportunity) for item in ranking_payload
    ):
        raise RuntimeError("ODS ranking stage returned an invalid payload")
    if not ranking_payload:
        raise RuntimeError("ODS ranking stage returned an empty shortlist")
    if not isinstance(blueprint_payload, BusinessBlueprint):
        raise RuntimeError("ODS BDNA stage returned an invalid payload")
    if not isinstance(validation_payload, ValidationReport):
        raise RuntimeError("ODS validation stage returned an invalid payload")

    return ODSAnalysisResult(
        session=session,
        ranked_opportunities=ranking_payload,
        blueprint=blueprint_payload,
        validation=validation_payload,
    )


def _failure_detail(session: ODSSession) -> str:
    """Return the most useful error generated by the failed workflow stage."""

    stage = session.current_stage
    if stage is not None:
        result = session.results.get(stage)
        if result is not None and result.errors:
            return "; ".join(result.errors)
    return session.audit_log[-1] if session.audit_log else "unknown failure"
